sudo: false

language: go
go:
  - 1.15.x
  - 1.16.x
  - tip

before_install:
  - go get -u golang.org/x/lint/golint honnef.co/go/tools/cmd/staticcheck

before_script:
  - go vet
  - golint -set_exit_status=1
  - staticcheck

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
  - cd ./v2
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
  - cd ../v3
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

