sudo: false

language: go
go:
  - 1.11.x
  - 1.12.x
  - tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep golang.org/x/lint/golint honnef.co/go/tools/cmd/staticcheck

install:
  - dep ensure

before_script:
  - go vet
  - golint -set_exit_status=1
  - staticcheck

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)

